services:
  cumplo-orchestrator:
    image: cumplo-orchestrator
    env_file: .env
    ports:
      - 8001:8080
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - CUMPLO_PYPI_BASE64_KEY
    volumes:
      - ./cumplo_orchestrator:/app/cumplo_orchestrator
